<div style="display:flex;justify-content:center">
    <img src="https://unram.ac.id/wp-content/uploads/2018/09/UNRAM-LOGO-FIX-STATUTA-.png" style="height: 100px" /> 
    <img src="https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/community/logos/python-logo-only.png" style="height: 100px"/> 
</div>


<h1 align="center">Pemodelan dan Simulasi Monte Carlo dalam Meningkatkan Pendapatan Penjualan Peralatan Motor</h1>

# Table of Content
<ul style="list-style:none">
    <li>
        <a href="#data-awal">Menampilkan data awal</a>
    </li>
    <li>Melakukan uji Proses Preprocessing Terhadap Data</li>
    <li>Melakukan uji hipotesis</li>
    <li>Melakukan uji normalitas</li>
    <li>Melakukan uji homogenitas</li>
    <li>Memilih salah satu metode analisis</li>
</ul>

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl

<h1 id="data-awal">Data Awal</h1>

In [4]:
excel_path = "dataset.xlsx"
df = pd.read_excel(excel_path,usecols=[1,2,3,4])
df.head(14)

Bulan  PM1  PM2  PM3
0       Jan   28   25   15
1       Feb   15   23   18
2       Mar   22   26   10
3       Apr    9    5   10
4       Mei   30   28   16
5       Jun   27   23   14
6       Jul   35   25   18
7       Agu   28   20   18
8       Sep   18   22   18
9       Okt   25   18   10
10      Nov   32   22   16
11      Des   20   25   20
12  Total :  289  262  183

In [9]:
pm1 = np.array(df["PM1"])
pm1 = np.delete(pm1,-1)
pm2 = np.array(df["PM2"])
pm2 = np.delete(pm2,-1)
pm3 = np.array(df["PM3"])
pm3 = np.delete(pm3,-1)
print(pm1)
print(pm2)
print(pm3)

[28 15 22  9 30 27 35 28 18 25 32 20]
[25 23 26  5 28 23 25 20 22 18 22 25]
[15 18 10 10 16 14 18 18 18 10 16 20]
